### ISSUE TITLE
Practica1_DiegoFidelSosaCruz

### ISSUE THREAD

**Issue by ghost** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Diego0501#1]
[DiegoSosa_Practica1_matediscretas.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Diego0501/files/12565417/DiegoSosa_Practica1_matediscretas.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25/25
RESULTADOS Y CONCLUSIONES 25/25

CALIFICACIÓN 20/20

CALIFICADO POR EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Excelente trabajo...muchas felicidades
